version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/gvisor"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
